### ISSUE TITLE
Duplicate date 27th October 2024

### ISSUE THREAD

**Issue by BaconFist** [werner-scholtz/kalender#93]
There is a duplicate of October 27. 2025.
I've verified it at https://werner-scholtz.github.io/kalender/ in Month and Multi Week view.

What i have seen so far:
- 27. double; once with 00:00 and once with 23:00
- days after 27. have time 23:00 instead of 00:00
- events added to a day with 23:00 will cause an exception in my project
- on this day daylight saving time changes from CEST/MESZ to CET/MEZ
- haven't seen any other day duplicates so far 
- the exception comes from here: https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/components/layout_delegates/multi_day_event_group_layout.dart#L62

![Exception_list dart](https://github.com/user-attachments/assets/65a49a6a-ca12-47b6-ab93-57ede55f80ea)
![multi_day_event_group_layout dart](https://github.com/user-attachments/assets/e921769f-fd7c-486a-b85d-9e400fed0237)

flutter --version
```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

pubspec.yaml
```
name: name
description: "description"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  uuid: ^4.5.1
  datetime_picker_formfield_new: ^2.1.0

  intl: any
  sqflite: ^2.4.0
  path: ^1.9.0
  share_plus: ^10.0.2
  flutter_archive: ^6.0.3
  file_picker: ^8.1.2
  open_file: ^3.5.8
  awesome_notifications: ^0.9.3+1
  flutter_localizations:
    sdk: flutter
  #flutter_carousel_widget: ^3.0.1
  url_launcher: ^6.3.1
  mime: ^1.0.6
  io: ^1.0.4
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  flutter_oss_licenses: ^3.0.2
  photo_view: ^0.15.0
  package_info: ^2.0.2
  kalender: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
```
